# Generated by Django 6.0.2 on 2026-04-11 17:22

import uuid
from django.db import migrations, models


def migrate_to_uuid(apps, schema_editor):
    """Migrate existing projects from integer IDs to UUIDs"""
    Project = apps.get_model('core', 'Project')
    for project in Project.objects.all():
        if isinstance(project.id, int):
            project.id = uuid.uuid4()
            project.save()


def reverse_migrate(apps, schema_editor):
    """Reverse migration - not supported for ID changes"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, editable=False),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # Data migration will happen in next step
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
