# Generated by Django 5.2.13 on 2026-04-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_id'),
        ('core', '0003_project_uuid'),
    ]

    operations = [
    ]
