# Generated by Django 5.2.13 on 2026-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0003_alter_project_id_0003_project_uuid'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$
DECLARE
    pk_constraint_name text;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'core_project'
          AND column_name = 'id'
          AND udt_name = 'uuid'
    ) THEN
        ALTER TABLE core_project ADD COLUMN id_new bigint;
        CREATE SEQUENCE IF NOT EXISTS core_project_id_new_seq OWNED BY core_project.id_new;
        ALTER TABLE core_project ALTER COLUMN id_new SET DEFAULT nextval('core_project_id_new_seq');
        UPDATE core_project SET id_new = nextval('core_project_id_new_seq') WHERE id_new IS NULL;
        ALTER TABLE core_project ALTER COLUMN id_new SET NOT NULL;

                SELECT conname
                INTO pk_constraint_name
                FROM pg_constraint
                WHERE conrelid = 'core_project'::regclass
                    AND contype = 'p'
                LIMIT 1;

                IF pk_constraint_name IS NOT NULL THEN
                        EXECUTE format('ALTER TABLE core_project DROP CONSTRAINT %I', pk_constraint_name);
                END IF;

        ALTER TABLE core_project DROP COLUMN id;
        ALTER TABLE core_project RENAME COLUMN id_new TO id;
        ALTER TABLE core_project ADD PRIMARY KEY (id);

        ALTER SEQUENCE core_project_id_new_seq OWNED BY core_project.id;
        ALTER TABLE core_project ALTER COLUMN id SET DEFAULT nextval('core_project_id_new_seq');
    END IF;
END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='project',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                )
            ],
        ),
    ]
